- name: Install MySQL Server and Create User
  hosts: your_server  # Replace with the target server or group of servers
  become: yes  # This will allow you to run tasks as sudo/root

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      become: yes

    - name: Install MySQL Server
      apt:
        name: mysql-server
        state: present
      become: yes

    - name: Start MySQL service
      service:
        name: mysql
        state: started
      become: yes

    - name: Secure MySQL installation
      command: mysql_secure_installation
      args:
        creates: /root/.my.cnf
      become: yes
      register: secure_installation

    - name: Set root password
      expect:
        command: "{{ secure_installation.stdout }}"
        responses:
          'Enter password for user root:': 'qwerty'
          'Change the root password?': 'n'
          'Remove anonymous users?': 'y'
          'Disallow root login remotely?': 'y'
          'Remove test database and access to it?': 'y'
          'Reload privilege tables now?': 'y'
      become: yes

    - name: Create MySQL User
      mysql_user: 'django_user'
        name: 'django_db'
        password: 'pa$$word'
        priv: '*.*:ALL'
        host: 'localhost'
        state: present
      become: yes
